// <auto-generated />
namespace IotDemoWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SLAB_Db_Setup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SLAB_Db_Setup));
        
        string IMigrationMetadata.Id
        {
            get { return "201612010331066_SLAB_Db_Setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
